/* File: pyraysummodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Oct 20 20:42:53 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *pyraysum_error;
static PyObject *pyraysum_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
/*need_cfuncs*/

/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_conf_def[] = {
  {"pi",0,{{-1}},NPY_DOUBLE},
  {"nlaymx",0,{{-1}},NPY_INT},
  {"a",5,{{3,3,3,3,30}},NPY_DOUBLE},
  {"thickn",1,{{30}},NPY_DOUBLE},
  {"rho",1,{{30}},NPY_DOUBLE},
  {"dp",0,{{-1}},NPY_DOUBLE},
  {"c",0,{{-1}},NPY_DOUBLE},
  {"rhof",0,{{-1}},NPY_DOUBLE},
  {"isoflg",1,{{30}},NPY_INT},
  {"dt",0,{{-1}},NPY_DOUBLE},
  {"slow",0,{{-1}},NPY_DOUBLE},
  {"baz",0,{{-1}},NPY_DOUBLE},
  {"evals",2,{{6,30}},NPY_CDOUBLE},
  {"evecs",3,{{6,6,30}},NPY_CDOUBLE},
  {"tui",3,{{3,3,30}},NPY_CDOUBLE},
  {"rui",3,{{3,3,30}},NPY_CDOUBLE},
  {"tdi",3,{{3,3,30}},NPY_CDOUBLE},
  {"rdi",3,{{3,3,30}},NPY_CDOUBLE},
  {NULL}
};
static void f2py_setup_conf(char *pi,char *nlaymx,char *a,char *thickn,char *rho,char *dp,char *c,char *rhof,char *isoflg,char *dt,char *slow,char *baz,char *evals,char *evecs,char *tui,char *rui,char *tdi,char *rdi) {
  int i_f2py=0;
  f2py_conf_def[i_f2py++].data = pi;
  f2py_conf_def[i_f2py++].data = nlaymx;
  f2py_conf_def[i_f2py++].data = a;
  f2py_conf_def[i_f2py++].data = thickn;
  f2py_conf_def[i_f2py++].data = rho;
  f2py_conf_def[i_f2py++].data = dp;
  f2py_conf_def[i_f2py++].data = c;
  f2py_conf_def[i_f2py++].data = rhof;
  f2py_conf_def[i_f2py++].data = isoflg;
  f2py_conf_def[i_f2py++].data = dt;
  f2py_conf_def[i_f2py++].data = slow;
  f2py_conf_def[i_f2py++].data = baz;
  f2py_conf_def[i_f2py++].data = evals;
  f2py_conf_def[i_f2py++].data = evecs;
  f2py_conf_def[i_f2py++].data = tui;
  f2py_conf_def[i_f2py++].data = rui;
  f2py_conf_def[i_f2py++].data = tdi;
  f2py_conf_def[i_f2py++].data = rdi;
}
extern void F_FUNC(f2pyinitconf,F2PYINITCONF)(void (*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_conf(void) {
  F_FUNC(f2pyinitconf,F2PYINITCONF)(f2py_setup_conf);
}
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/
/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "pyraysum",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_pyraysum(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = pyraysum_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module pyraysum (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'pyraysum' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  conf --- pi,nlaymx,a,thickn,rho,dp,c,rhof,isoflg,dt,slow,baz,evals,evecs,tui,rui,tdi,rdi"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  pyraysum_error = PyErr_NewException ("pyraysum.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_pyraysum_error", pyraysum_error);
  Py_DECREF(pyraysum_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }
/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "conf", PyFortranObject_New(f2py_conf_def,f2py_init_conf));/*eof initf90modhooks*/
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"pyraysum");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
