!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitconf(f2pysetupfunc)
      use conf, only : pi
      use conf, only : nlaymx
      use conf, only : a
      use conf, only : thickn
      use conf, only : rho
      use conf, only : dp
      use conf, only : c
      use conf, only : rhof
      use conf, only : isoflg
      use conf, only : dt
      use conf, only : slow
      use conf, only : baz
      use conf, only : evals
      use conf, only : evecs
      use conf, only : tui
      use conf, only : rui
      use conf, only : tdi
      use conf, only : rdi
      external f2pysetupfunc
      call f2pysetupfunc(pi,nlaymx,a,thickn,rho,dp,c,rhof,isoflg,dt,slow&
     &,baz,evals,evecs,tui,rui,tdi,rdi)
      end subroutine f2pyinitconf


